### ISSUE TITLE
Overridden config values are still in forms, prevent form save.

### ISSUE THREAD

**Issue by rosiel** [Islandora-Devops/isle-site-template#12]
A number of values such as the Broker URI (Islandora Settings form) are set using Drupal's config override by specifying values in the settings.php file. However, the values that an admin sees in the form are those provided by the starter site (which is confusing, as the admin can't see what value is actually being used). Furthermore, for all forms with validation (including the Islandora settings form) the admin cannot change any settings in that form without first finding the valid value for that setting. This is frustrating and time-consuming.

<img width="1108" alt="Screenshot 2023-08-11 at 2 20 25 PM" src="https://github.com/Islandora-Devops/isle-site-template/assets/1943338/066e8fb7-8ab0-40c1-86f4-7f90f7b2a22a">

**Comment by rosiel** [comment]
This could be mitigated if we install  [Config Override Warn](https://www.drupal.org/project/config_override_warn)

**Comment by nigelgbanks** [comment]
This is oddly [intentional](https://www.drupal.org/docs/drupal-apis/configuration-api/configuration-override-system#s-global-overrides), though they plan to change the behavior in D11, [apparently](https://www.drupal.org/project/drupal/issues/2408549).

If we were to install [Config Override Warn](https://www.drupal.org/project/config_override_warn), that would have to be done on the https://github.com/Islandora-Devops/islandora-starter-site repository.

**Comment by nigelgbanks** [comment]
Closing this as I've raised an issue in https://github.com/Islandora-Devops/islandora-starter-site/issues/112
