### ISSUE TITLE
Developing the Starter Site (as a use case) is hindered by uninstalling `sqlite` and `pgsql`.

### ISSUE THREAD

**Issue by rosiel** [Islandora-Devops/isle-site-template#36]
As part of the final steps of the site template, the site template uninstalls the sqlite and pgsql drivers (that come as drupal modules). This is, without a doubt, the best practice for real sites.

But this has caught me at least 3 times when making PRs against the Starter Site. Tests fail because sqlite is needed for tests (at least it catches this though!).

The Site template is the best candidate for developing the starter site because other than this, the config remains untouched. ISLE DC on the other hand sets a number of config variables which have to be undone before they can be committed to the starter site.

I would propose that when using `--profile dev` we don't uninstall these modules. Perhaps include another line in the README for how to uninstall them (since the site template installation already requires about 5 lines of copy-pastery, what's one more?)

**Comment by joshdentremont** [comment]
I don't think we could leave them installed on dev, but not in production, because we export our config from dev to production, which includes the modules that are installed.

Is the issue that you are working on the starter site and in the process are exporting the config, which then does not have those two modules installed?

Looks like those modules are being uninstalled via drush here: https://github.com/Islandora-Devops/isle-site-template/blob/dfea0162b56497d5c1be9056d4f1711ce045d841/drupal/rootfs/etc/s6-overlay/scripts/install.sh#L14 which should only happen during the initial setup. Would it be possible to just add them back in right after that runs, when you are working on the starter site?

For example, if you are running setup.sh to spin up a new site, could you then run `pm:install pgsql sqlite`. Or maybe we could create a modified version of setup.sh for folks working on the starter site that does that all in the same script?
