### ISSUE TITLE
Tests failing inconsistently

### ISSUE THREAD

**Issue by joshdentremont** [Islandora-Devops/isle-site-template#62]
Looks like tests for this repo are failling sometimes and succeeding other times, despite nothing changing. On failures, ping is returning 500 errors when running ping.sh

There were no changes to the main branch in this time period:
<img width="1257" alt="image" src="https://github.com/user-attachments/assets/fcb39c4c-3440-44f1-9313-7f6f68ba3338">

**Comment by joecorall** [comment]
[The test jobs you see on the actions tab](https://github.com/Islandora-Devops/isle-site-template/actions) are nightly builds to ensure [islandora-starter-site](https://github.com/Islandora-Devops/islandora-starter-site), [isle-buildkit](https://github.com/Islandora-Devops/isle-buildkit), and this repo work for fresh installs.

The tests were failing last week due to a drush upgrade in islandora-starter site and was resolved with https://github.com/Islandora-Devops/isle-site-template/pull/58

The tests are failing this week due to the old isle-buildkit tag in this repo not working with the buildkit 3.4 tag. This is resolved with https://github.com/Islandora-Devops/isle-site-template/pull/63
